Maxon:
  config_run_sdo_verify_timeout: 50000
  print_debug_messages: true
  use_raw_commands: true
  drive_state_change_min_timeout: 2000
  drive_state_change_max_timeout: 10000 # microseconds
  min_number_of_successful_target_state_readings: 5
  display_error_codes: true
  disable_configuration_on_startup: false
  interpolation_time_period_ms: 1 # in ms. "0" disables demand value interpolation.
  # > 0 enables demand value interpolation. Target Position (and offset), Velocity
  # (and offset) are written cyclically with the interpolation time period.

Reading:
  force_append_equal_error: true
  force_append_equal_fault: false
  error_storage_capacity: 100
  fault_storage_capacity: 100

Hardware:
  mode_of_operation:
  - CyclicSynchronousPositionMode
  position_encoder_resolution: 4096 # [counts/rev]
  gear_ratio: [1, 1] # Absolute Reduction in Datasheet, should be positive and less than 2^32 - 1
  motor_constant: 1.0 # Not being used anywhere in SDK from my observation
  working_voltage: 48 # [V]
  pole_pairs: 1 # Number of pole pairs
  speed_constant: 1300 # [rpm/V]
  torque_constant: 0.00733 # [Nm/A], max value is 10,000,000
  max_current: 2.06 # [A]
  nominal_current: 1.03 # [A]
  min_position: 0
  max_position: 0 # Disable checks, software position limits, can be b/w -(2^31 - 1) to (2^31 - 1)
  
  max_profile_velocity: 50 # [rad/s], max value is 224.883 rad/s. Check EPOS4 firmware ref.
  quick_stop_decel: 10000 # [rpm/s], max value bounded by max_acceleration (which defaults to 4'294'967'295)
  profile_decel: 10000 # [rpm/s] , max value bounded by max_acceleration (which defaults to 4'294'967'295)
  follow_error_window: 20000 # [inc]

  current_p_gain: 3.262434 # [V/A]
  current_i_gain: 17.884582 # [mV/(A*s)]
  position_p_gain: 3.452142 # [A/rad]
  position_i_gain: 32.994732 # [A/(rad*s)]
  position_d_gain: 0.021841 # [(A*s)/rad]
  velocity_p_gain: 0.091629 # [(A*s)/rad]
  velocity_i_gain: 6.573788 # [A/rad]

  motor_type: 10 # Changes certain value ranges. For eg: max_motor_speed
  # Allowed values for motor type: (check EPOS4 firmware ref)
  # 1 : Brushed DC (max_motor_speed limit = 100000)
  # 10: Brushless DC sine commutated (max_motor_speed limit = 50000/pole_pairs)
  # 11: Brushless DC block commutated (max_motor_speed limit = 100000/pole_pairs)