Maxon:
  config_run_sdo_verify_timeout: 50000
  print_debug_messages: true
  use_raw_commands: true
  drive_state_change_min_timeout: 2000
  drive_state_change_max_timeout: 10000 # microseconds
  min_number_of_successful_target_state_readings: 5
  display_error_codes: true
  disable_configuration_on_startup: false

Reading:
  force_append_equal_error: true
  force_append_equal_fault: false
  error_storage_capacity: 100
  fault_storage_capacity: 100

Hardware:
  mode_of_operation:
  - CyclicSynchronousPositionMode
  position_encoder_resolution: 4096 # Counts per revolution
  gear_ratio: [1, 1] # Absolute Reduction in Datasheet, should be positive and less than 2^32 - 1
  motor_constant: 1.0 # Not being used anywhere in SDK from my observation
  working_voltage: 48 # V
  pole_pairs: 1 # Number of pole pairs
  speed_constant: 1300 # RPM/V so min^-1/V
  torque_constant: 0.00733 # Nm/A max val is 10,000,000
  max_current: 2.06 # A
  nominal_current: 1.03 # A
  min_position: 0
  max_position: 0 # Disable checks, software position limits, can be b/w -(2^31 - 1) to (2^31 - 1)
  max_profile_velocity: 50 # in rad/s
  # NOTE: due to velocity unit being micro-RPM, the max value is 224.883 rad/s. Check EPOS4 firmware ref.
  # Note that the limit gets modified by max_gear_input_speed.
  max_gear_input_speed: 100000 # RPM, max value is 100,000 RPM.
  quick_stop_decel: 10000 # rpm/s , max value bounded by max_acceleration (which defaults to 4'294'967'295)
  profile_decel: 10000 # rpm/s , max value bounded by max_acceleration (which defaults to 4'294'967'295)
  follow_error_window: 20000 # Check startup params in EPOS studio
  # All Gains follow their SI units, (except current i gain)
  current_p_gain: 3.262434 # V/A, Check OD from EPOS Studio (OD is in mV/A)
  current_i_gain: 17.884582 # mV/(A*s), Check OD from EPOS Studio (OD is in mV/(A*ms))
  position_p_gain: 3.452142 # A/rad, Check OD from EPOS Studio (OD is in mA/rad)
  position_i_gain: 32.994732 # A/(rad*s), Check OD from EPOS Studio (OD is in mA/(rad*s))
  position_d_gain: 0.021841 # A*s/rad, Check OD from EPOS Studio (OD is in mA*s/rad)
  velocity_p_gain: 0.091629 # A*s/rad, Check OD from EPOS Studio (OD is in mA*s/rad)
  velocity_i_gain: 6.573788 # A/rad, Check OD from EPOS Studio (OD is in mA/rad)

  motor_type: 10 # Changes certain value ranges. For eg: max_motor_speed
  # Allowed values for motor type: (check EPOS4 firmware ref)
  # 1 : Brushed DC (max_motor_speed limit = 100000)
  # 10: Brushless DC sine commutated (max_motor_speed limit = 50000/pole_pairs)
  # 11: Brushless DC block commutated (max_motor_speed limit = 100000/pole_pairs)