Maxon:
  config_run_sdo_verify_timeout: 50000
  print_debug_messages: true
  use_raw_commands: false
  drive_state_change_min_timeout: 2000
  drive_state_change_max_timeout: 10000 # microseconds
  min_number_of_successful_target_state_readings: 5
  display_error_codes: true
  disable_configuration_on_startup: false

Reading:
  force_append_equal_error: true
  force_append_equal_fault: false
  error_storage_capacity: 100
  fault_storage_capacity: 100

# Configuring the test DCX12L EB SL 12V motor with the EPOS4 controller
# Purely for testing purposes and not for final use with the robot

Hardware:
  mode_of_operation:
  - CyclicSynchronousPositionMode
  position_encoder_resolution: 1024 # Counts per revolution
  gear_ratio: [4761, 169] # Absolute Reduction in Datasheet
  motor_constant: 1.0
  working_voltage: 12 # V
  pole_pairs: 1 # Number of pole pairs
  speed_constant: 741 # RPM/V so min^-1/V
  torque_constant: 0.0129 # Nm/A
  max_current: 0.15 # A
  nominal_current: 0.309 # A
  min_position: 0
  max_position: 0 # Disable checks, software position limits
  max_profile_velocity: 137 # max. permissible speed, RPM, actual is 11k, but keeping a safe buffer
  quick_stop_decel: 10000
  profile_decel: 10000
  follow_error_window: 20000 # Check startup params in EPOS studio
  # All Gains follow their SI units
  current_p_gain: 9.465886 # V/A, Check OD from EPOS Studio
  current_i_gain: 119671.118 # V/(A*s), Check OD from EPOS Studio
  position_p_gain: 0.183623 # A/rad, Check OD from EPOS Studio
  position_i_gain: 7.691592 # A/(rad*s), Check OD from EPOS Studio
  position_d_gain: 0.001424 # A*s/rad, Check OD from EPOS Studio
  velocity_p_gain: 0.000978 # A*s/rad, Check OD from EPOS Studio 
  velocity_i_gain: 0.061583 # A*s^2/rad, Check OD from EPOS Studio