# Example config file for Nanotec Drives
Nanotec:
  config_run_sdo_verify_timeout: 50000
  drive_state_change_min_timeout: 2000
  drive_state_change_max_timeout: 10000
  min_number_of_successful_target_state_readings: 10
  interpolation_time_period_ms: 1 # Leave this to >= 1, never set it to 0

Reading:
  force_append_equal_error: true
  force_append_equal_fault: false
  error_storage_capacity: 100
  fault_storage_capacity: 100

Hardware:
  mode_of_operation:
    - CyclicSynchronousPositionMode
  pole_pairs: 50  
  max_motor_current_mA: 3000
  rated_current_mA: 2500
  max_motor_speed: 500
  max_current_percentage: 1000 # percent value * 10
  i2t_max_duration_of_peak_ms: 100 # 100 is recommended
  clock_direction_multiplier: 16 # 128 = quarter step/pulse (800 steps/rev), 512 = normal step/pulse (200 steps/rev)
  clock_direction_divider: 1
  limit_switch_negative_en: true
  limit_switch_positive_en: false
  limit_switch_homing_en: false
  limit_switch_negative_function_inverted: false 
  limit_switch_positive_function_inverted: false 
  limit_switch_homing_function_inverted: false 

  software_position_limit_min: -100000
  software_position_limit_max: 100000
  position_range_limit_min: -100000
  position_range_limit_max: 100000
  gear_ratio_motor_revolutions: 1
  gear_ratio_shaft_revolutions: 1
  
  # position_unit: 267653120  # 0xFF41000 for tenths of a degree, 3600 = 1 full mechanical rev
  # velocity_unit: 11814656 # 0x00B44700 for rpm

AutoSetup:
  auto_setup_en: false
  auto_setup_timeout_ms: 30000

Homing:
  homing_en: true
  home_offset: 60957 # Set zero position <- Range is 60957
  homing_method: 17
  homing_speed_zero_search: 100 #10deg/s
  homing_speed_switch_search: 100 #10deg/s
  homing_acceleration: 100
  minimum_current_for_block_detection_mA: 1200
  period_of_blocking_ms: 200
  homing_timeout_ms: 60000